server:
  port: 9002

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=user_service
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: sapassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400
resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttempts: 3
        waitDuration: 4s
  ratelimiter:
    instances:
      basicExample:
        limitForPeriod: 1
        limitRefreshPeriod: 5s
        timeoutDuration: 3s